//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VYMSolucion.Web.ServiceReferenceCatalogo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCatalogo.IServiceCatalogo")]
    public interface IServiceCatalogo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogo/ListaGenero", ReplyAction="http://tempuri.org/IServiceCatalogo/ListaGeneroResponse")]
        VYMSolucion.Model.ComboModel[] ListaGenero();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogo/ListaGenero", ReplyAction="http://tempuri.org/IServiceCatalogo/ListaGeneroResponse")]
        System.Threading.Tasks.Task<VYMSolucion.Model.ComboModel[]> ListaGeneroAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogo/ListaEstadoCivil", ReplyAction="http://tempuri.org/IServiceCatalogo/ListaEstadoCivilResponse")]
        VYMSolucion.Model.ComboModel[] ListaEstadoCivil();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogo/ListaEstadoCivil", ReplyAction="http://tempuri.org/IServiceCatalogo/ListaEstadoCivilResponse")]
        System.Threading.Tasks.Task<VYMSolucion.Model.ComboModel[]> ListaEstadoCivilAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogo/ListaPerfiles", ReplyAction="http://tempuri.org/IServiceCatalogo/ListaPerfilesResponse")]
        VYMSolucion.Model.ComboModel[] ListaPerfiles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogo/ListaPerfiles", ReplyAction="http://tempuri.org/IServiceCatalogo/ListaPerfilesResponse")]
        System.Threading.Tasks.Task<VYMSolucion.Model.ComboModel[]> ListaPerfilesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogo/ListaTipoSangre", ReplyAction="http://tempuri.org/IServiceCatalogo/ListaTipoSangreResponse")]
        VYMSolucion.Model.ComboModel[] ListaTipoSangre();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogo/ListaTipoSangre", ReplyAction="http://tempuri.org/IServiceCatalogo/ListaTipoSangreResponse")]
        System.Threading.Tasks.Task<VYMSolucion.Model.ComboModel[]> ListaTipoSangreAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogo/ListaParentesco", ReplyAction="http://tempuri.org/IServiceCatalogo/ListaParentescoResponse")]
        VYMSolucion.Model.ComboModel[] ListaParentesco();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogo/ListaParentesco", ReplyAction="http://tempuri.org/IServiceCatalogo/ListaParentescoResponse")]
        System.Threading.Tasks.Task<VYMSolucion.Model.ComboModel[]> ListaParentescoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogo/ListaFechaDias", ReplyAction="http://tempuri.org/IServiceCatalogo/ListaFechaDiasResponse")]
        VYMSolucion.Model.ComboModel[] ListaFechaDias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogo/ListaFechaDias", ReplyAction="http://tempuri.org/IServiceCatalogo/ListaFechaDiasResponse")]
        System.Threading.Tasks.Task<VYMSolucion.Model.ComboModel[]> ListaFechaDiasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogo/ListaFechaMeses", ReplyAction="http://tempuri.org/IServiceCatalogo/ListaFechaMesesResponse")]
        VYMSolucion.Model.ComboModel[] ListaFechaMeses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogo/ListaFechaMeses", ReplyAction="http://tempuri.org/IServiceCatalogo/ListaFechaMesesResponse")]
        System.Threading.Tasks.Task<VYMSolucion.Model.ComboModel[]> ListaFechaMesesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogo/ListaFechaAnios", ReplyAction="http://tempuri.org/IServiceCatalogo/ListaFechaAniosResponse")]
        VYMSolucion.Model.ComboModel[] ListaFechaAnios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogo/ListaFechaAnios", ReplyAction="http://tempuri.org/IServiceCatalogo/ListaFechaAniosResponse")]
        System.Threading.Tasks.Task<VYMSolucion.Model.ComboModel[]> ListaFechaAniosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogo/ListaFechaAniosMenorEdad", ReplyAction="http://tempuri.org/IServiceCatalogo/ListaFechaAniosMenorEdadResponse")]
        VYMSolucion.Model.ComboModel[] ListaFechaAniosMenorEdad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogo/ListaFechaAniosMenorEdad", ReplyAction="http://tempuri.org/IServiceCatalogo/ListaFechaAniosMenorEdadResponse")]
        System.Threading.Tasks.Task<VYMSolucion.Model.ComboModel[]> ListaFechaAniosMenorEdadAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCatalogoChannel : VYMSolucion.Web.ServiceReferenceCatalogo.IServiceCatalogo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCatalogoClient : System.ServiceModel.ClientBase<VYMSolucion.Web.ServiceReferenceCatalogo.IServiceCatalogo>, VYMSolucion.Web.ServiceReferenceCatalogo.IServiceCatalogo {
        
        public ServiceCatalogoClient() {
        }
        
        public ServiceCatalogoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCatalogoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCatalogoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCatalogoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VYMSolucion.Model.ComboModel[] ListaGenero() {
            return base.Channel.ListaGenero();
        }
        
        public System.Threading.Tasks.Task<VYMSolucion.Model.ComboModel[]> ListaGeneroAsync() {
            return base.Channel.ListaGeneroAsync();
        }
        
        public VYMSolucion.Model.ComboModel[] ListaEstadoCivil() {
            return base.Channel.ListaEstadoCivil();
        }
        
        public System.Threading.Tasks.Task<VYMSolucion.Model.ComboModel[]> ListaEstadoCivilAsync() {
            return base.Channel.ListaEstadoCivilAsync();
        }
        
        public VYMSolucion.Model.ComboModel[] ListaPerfiles() {
            return base.Channel.ListaPerfiles();
        }
        
        public System.Threading.Tasks.Task<VYMSolucion.Model.ComboModel[]> ListaPerfilesAsync() {
            return base.Channel.ListaPerfilesAsync();
        }
        
        public VYMSolucion.Model.ComboModel[] ListaTipoSangre() {
            return base.Channel.ListaTipoSangre();
        }
        
        public System.Threading.Tasks.Task<VYMSolucion.Model.ComboModel[]> ListaTipoSangreAsync() {
            return base.Channel.ListaTipoSangreAsync();
        }
        
        public VYMSolucion.Model.ComboModel[] ListaParentesco() {
            return base.Channel.ListaParentesco();
        }
        
        public System.Threading.Tasks.Task<VYMSolucion.Model.ComboModel[]> ListaParentescoAsync() {
            return base.Channel.ListaParentescoAsync();
        }
        
        public VYMSolucion.Model.ComboModel[] ListaFechaDias() {
            return base.Channel.ListaFechaDias();
        }
        
        public System.Threading.Tasks.Task<VYMSolucion.Model.ComboModel[]> ListaFechaDiasAsync() {
            return base.Channel.ListaFechaDiasAsync();
        }
        
        public VYMSolucion.Model.ComboModel[] ListaFechaMeses() {
            return base.Channel.ListaFechaMeses();
        }
        
        public System.Threading.Tasks.Task<VYMSolucion.Model.ComboModel[]> ListaFechaMesesAsync() {
            return base.Channel.ListaFechaMesesAsync();
        }
        
        public VYMSolucion.Model.ComboModel[] ListaFechaAnios() {
            return base.Channel.ListaFechaAnios();
        }
        
        public System.Threading.Tasks.Task<VYMSolucion.Model.ComboModel[]> ListaFechaAniosAsync() {
            return base.Channel.ListaFechaAniosAsync();
        }
        
        public VYMSolucion.Model.ComboModel[] ListaFechaAniosMenorEdad() {
            return base.Channel.ListaFechaAniosMenorEdad();
        }
        
        public System.Threading.Tasks.Task<VYMSolucion.Model.ComboModel[]> ListaFechaAniosMenorEdadAsync() {
            return base.Channel.ListaFechaAniosMenorEdadAsync();
        }
    }
}
