//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VYMSolucion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendaEntidadPersona
    {
        public long IdAgendaEntidadPersona { get; set; }
        public long IdEntidadPersonaProf { get; set; }
        public Nullable<long> IdEntidadPersonaCliente { get; set; }
        public Nullable<long> IdCentroAdministrativo { get; set; }
        public Nullable<System.DateTime> FechaTurnoDesde { get; set; }
        public Nullable<System.DateTime> FechaTurnoHasta { get; set; }
        public long EstadoTurno { get; set; }
        public bool EsConfirmadaCita { get; set; }
        public Nullable<int> TiempoViajeMinsProf { get; set; }
        public Nullable<int> TiempoViajeMinsCliente { get; set; }
        public Nullable<long> EstadoCita { get; set; }
        public string MotivoConsulta { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> TiempoEstimadaCitaMins { get; set; }
        public long TipoEvento { get; set; }
        public Nullable<bool> AlertaRecordatorioProf { get; set; }
        public Nullable<int> TiempoAlertaProf { get; set; }
        public Nullable<bool> AlertaRecordatotioCliente { get; set; }
        public Nullable<int> TiempoAlertaCliente { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaUltModificacion { get; set; }
        public long IdUsuarioCreacion { get; set; }
        public Nullable<long> IdUsuarioModificacion { get; set; }
        public bool EsActiva { get; set; }
    
        public virtual CentroAdministrativo CentroAdministrativo { get; set; }
        public virtual EntidadPersona EntidadPersona { get; set; }
        public virtual EntidadPersona EntidadPersona1 { get; set; }
    }
}
