//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VYMSolucion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentroAdministrativo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CentroAdministrativo()
        {
            this.AgendaEntidadPersonas = new HashSet<AgendaEntidadPersona>();
            this.CentroAdministrativo1 = new HashSet<CentroAdministrativo>();
        }
    
        public long IdCentroAdministrativo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public long IdUbicacionGeografica { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string UrlMapa { get; set; }
        public Nullable<long> IdCentroAdministrativoPadre { get; set; }
        public bool EsActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgendaEntidadPersona> AgendaEntidadPersonas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CentroAdministrativo> CentroAdministrativo1 { get; set; }
        public virtual CentroAdministrativo CentroAdministrativo2 { get; set; }
        public virtual UbicacionGeografica UbicacionGeografica { get; set; }
    }
}
