//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VYMSolucion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntidadPersona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntidadPersona()
        {
            this.AntecedentesPatologicosOAlergias = new HashSet<AntecedentesPatologicosOAlergia>();
            this.AgendaEntidadPersonas = new HashSet<AgendaEntidadPersona>();
            this.AgendaEntidadPersonas1 = new HashSet<AgendaEntidadPersona>();
            this.EntidadPersona1 = new HashSet<EntidadPersona>();
            this.PerfilProfesionals = new HashSet<PerfilProfesional>();
            this.PerfilUsuarios = new HashSet<PerfilUsuario>();
        }
    
        public long IdEntidadPersona { get; set; }
        public string CedulaRuc { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public long IdUbicacionGeograficaNacim { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public long Genero { get; set; }
        public long EstadoCivil { get; set; }
        public string TelefonoMovil { get; set; }
        public string TelefonoConvencional { get; set; }
        public string Direccion { get; set; }
        public long IdUbicacionGeograficaResid { get; set; }
        public Nullable<decimal> PesoNacimiento { get; set; }
        public Nullable<decimal> EstaturaNacimiento { get; set; }
        public Nullable<decimal> PerimetroCefalico { get; set; }
        public Nullable<decimal> Apgar { get; set; }
        public Nullable<long> TipoParto { get; set; }
        public Nullable<int> SemanasGestacion { get; set; }
        public Nullable<decimal> IndiceMasaCorporal { get; set; }
        public Nullable<long> TipoSangre { get; set; }
        public Nullable<long> ConQuienvive { get; set; }
        public string Observaciones { get; set; }
        public Nullable<long> Profesion { get; set; }
        public Nullable<long> Ocupacion { get; set; }
        public Nullable<long> Parentesco { get; set; }
        public Nullable<long> Religion { get; set; }
        public Nullable<long> Etnia { get; set; }
        public string Correo { get; set; }
        public string NombreUsuario { get; set; }
        public string Contrasena { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaUltModificacion { get; set; }
        public long IdUsuarioCreacion { get; set; }
        public Nullable<long> IdUsuarioModificacion { get; set; }
        public Nullable<long> IdEntidadPersonaPadre { get; set; }
        public bool EsActivo { get; set; }
    
        public virtual UbicacionGeografica UbicacionGeografica { get; set; }
        public virtual UbicacionGeografica UbicacionGeografica1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AntecedentesPatologicosOAlergia> AntecedentesPatologicosOAlergias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgendaEntidadPersona> AgendaEntidadPersonas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgendaEntidadPersona> AgendaEntidadPersonas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadPersona> EntidadPersona1 { get; set; }
        public virtual EntidadPersona EntidadPersona2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerfilProfesional> PerfilProfesionals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerfilUsuario> PerfilUsuarios { get; set; }
    }
}
