//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VYMSolucion.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VYMCoreEntities : DbContext
    {
        public VYMCoreEntities()
            : base("name=VYMCoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivacionUsuario> ActivacionUsuarios { get; set; }
        public virtual DbSet<Catalogo> Catalogoes { get; set; }
        public virtual DbSet<CentroAdministrativo> CentroAdministrativoes { get; set; }
        public virtual DbSet<UbicacionGeografica> UbicacionGeograficas { get; set; }
        public virtual DbSet<AntecedentesPatologicosOAlergia> AntecedentesPatologicosOAlergias { get; set; }
        public virtual DbSet<EntidadPersona> EntidadPersonas { get; set; }
        public virtual DbSet<PerfilProfesional> PerfilProfesionals { get; set; }
        public virtual DbSet<PerfilUsuario> PerfilUsuarios { get; set; }
        public virtual DbSet<AgendaEntidadPersona> AgendaEntidadPersonas { get; set; }
    }
}
