//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceComun {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceComun() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceComun", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agendar cita.
        /// </summary>
        internal static string AgendarCita {
            get {
                return ResourceManager.GetString("AgendarCita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agendar citas médicas.
        /// </summary>
        internal static string AgendarCitasMedicas {
            get {
                return ResourceManager.GetString("AgendarCitasMedicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alerta.
        /// </summary>
        internal static string Alerta {
            get {
                return ResourceManager.GetString("Alerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a año.
        /// </summary>
        internal static string Anio {
            get {
                return ResourceManager.GetString("Anio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        internal static string Apellidos {
            get {
                return ResourceManager.GetString("Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cédula/RUC.
        /// </summary>
        internal static string CedulaRuc {
            get {
                return ResourceManager.GetString("CedulaRuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centros Administrativos.
        /// </summary>
        internal static string CentrosAdministrativos {
            get {
                return ResourceManager.GetString("CentrosAdministrativos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        internal static string Ciudad {
            get {
                return ResourceManager.GetString("Ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación.
        /// </summary>
        internal static string Confirmacion {
            get {
                return ResourceManager.GetString("Confirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Contrasena {
            get {
                return ResourceManager.GetString("Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repetir Contraseña.
        /// </summary>
        internal static string ContrasenaRepetir {
            get {
                return ResourceManager.GetString("ContrasenaRepetir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a día.
        /// </summary>
        internal static string Dia {
            get {
                return ResourceManager.GetString("Dia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        internal static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escoger.
        /// </summary>
        internal static string Escoger {
            get {
                return ResourceManager.GetString("Escoger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado Civil.
        /// </summary>
        internal static string EstadoCivil {
            get {
                return ResourceManager.GetString("EstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Genero.
        /// </summary>
        internal static string Genero {
            get {
                return ResourceManager.GetString("Genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mes.
        /// </summary>
        internal static string Mes {
            get {
                return ResourceManager.GetString("Mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        internal static string Nombres {
            get {
                return ResourceManager.GetString("Nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        internal static string Nuevo {
            get {
                return ResourceManager.GetString("Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        internal static string Observaciones {
            get {
                return ResourceManager.GetString("Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        internal static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parentesco.
        /// </summary>
        internal static string Parentesco {
            get {
                return ResourceManager.GetString("Parentesco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia.
        /// </summary>
        internal static string Provincia {
            get {
                return ResourceManager.GetString("Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        internal static string Regresar {
            get {
                return ResourceManager.GetString("Regresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reiniciar.
        /// </summary>
        internal static string Reiniciar {
            get {
                return ResourceManager.GetString("Reiniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione ....
        /// </summary>
        internal static string Seleccione {
            get {
                return ResourceManager.GetString("Seleccione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        internal static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono Convencional.
        /// </summary>
        internal static string TelefonoConvencional {
            get {
                return ResourceManager.GetString("TelefonoConvencional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono Movil.
        /// </summary>
        internal static string TelefonoMovil {
            get {
                return ResourceManager.GetString("TelefonoMovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Sangre.
        /// </summary>
        internal static string TipoSangre {
            get {
                return ResourceManager.GetString("TipoSangre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación Genográfica.
        /// </summary>
        internal static string UbicacionGeografica {
            get {
                return ResourceManager.GetString("UbicacionGeografica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        internal static string Ver {
            get {
                return ResourceManager.GetString("Ver", resourceCulture);
            }
        }
    }
}
