//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceLayout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLayout() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceLayout", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activar Cuenta.
        /// </summary>
        internal static string ActivarCuenta {
            get {
                return ResourceManager.GetString("ActivarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activar/Desactivar.
        /// </summary>
        internal static string ActivarDesactivar {
            get {
                return ResourceManager.GetString("ActivarDesactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido(a)!.
        /// </summary>
        internal static string Bienvenido {
            get {
                return ResourceManager.GetString("Bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        internal static string CerrarSesion {
            get {
                return ResourceManager.GetString("CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Contrasena {
            get {
                return ResourceManager.GetString("Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a vymsolucion@gmail.com.
        /// </summary>
        internal static string CorreoEmpresa {
            get {
                return ResourceManager.GetString("CorreoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crea tu cuenta.
        /// </summary>
        internal static string CreaCuenta {
            get {
                return ResourceManager.GetString("CreaCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credenciales Invalidas.
        /// </summary>
        internal static string CredencialesInvalidas {
            get {
                return ResourceManager.GetString("CredencialesInvalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Generales.
        /// </summary>
        internal static string DatosGenerales {
            get {
                return ResourceManager.GetString("DatosGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de Nacimiento.
        /// </summary>
        internal static string DatosNacimiento {
            get {
                return ResourceManager.GetString("DatosNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de Residencia.
        /// </summary>
        internal static string DatosResidencia {
            get {
                return ResourceManager.GetString("DatosResidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} - {1} de {2} registros.
        /// </summary>
        internal static string DisplayDatos {
            get {
                return ResourceManager.GetString("DisplayDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existen registros.
        /// </summary>
        internal static string EmptyDatos {
            get {
                return ResourceManager.GetString("EmptyDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string Espanol {
            get {
                return ResourceManager.GetString("Espanol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtros.
        /// </summary>
        internal static string Filtros {
            get {
                return ResourceManager.GetString("Filtros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a la primera página.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese nombre de usuario y contraseña.
        /// </summary>
        internal static string IngresarCredenciales {
            get {
                return ResourceManager.GetString("IngresarCredenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar.
        /// </summary>
        internal static string Iniciar {
            get {
                return ResourceManager.GetString("Iniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string IniciarSesion {
            get {
                return ResourceManager.GetString("IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a la ultima página.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        internal static string Limpiar {
            get {
                return ResourceManager.GetString("Limpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a su cuenta se encuentra activa .
        /// </summary>
        internal static string MensajeActivacionCuenta {
            get {
                return ResourceManager.GetString("MensajeActivacionCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceda a su cuenta.
        /// </summary>
        internal static string MensajeBotonIniciarSesion {
            get {
                return ResourceManager.GetString("MensajeBotonIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resuelve tus tudas de salud y bienestar.
        /// </summary>
        internal static string MensajeBotonPaciente {
            get {
                return ResourceManager.GetString("MensajeBotonPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejora tu visibilidad online y consigue nuevos pacientes.
        /// </summary>
        internal static string MensajeBotonProfesional {
            get {
                return ResourceManager.GetString("MensajeBotonProfesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar datos del paciente.
        /// </summary>
        internal static string MensajeBuscarDatosPaciente {
            get {
                return ResourceManager.GetString("MensajeBuscarDatosPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos Obligatorios.
        /// </summary>
        internal static string MensajeCamposObligatorios {
            get {
                return ResourceManager.GetString("MensajeCamposObligatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para registrarte debes seleccionar qué tipo de usuario eres.
        /// </summary>
        internal static string MensajeRegistrarCuenta {
            get {
                return ResourceManager.GetString("MensajeRegistrarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido! se ha enviado un correo para validar su información.
        /// </summary>
        internal static string MensajeRegistroCorrecto {
            get {
                return ResourceManager.GetString("MensajeRegistroCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registre datos del paciente.
        /// </summary>
        internal static string MensajeRegistroPaciente {
            get {
                return ResourceManager.GetString("MensajeRegistroPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú del.
        /// </summary>
        internal static string MenuDel {
            get {
                return ResourceManager.GetString("MenuDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a la siguiente página.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VYM Solución.
        /// </summary>
        internal static string NombreEmpresa {
            get {
                return ResourceManager.GetString("NombreEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        internal static string Nuevo {
            get {
                return ResourceManager.GetString("Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        internal static string Observaciones {
            get {
                return ResourceManager.GetString("Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paciente.
        /// </summary>
        internal static string Paciente {
            get {
                return ResourceManager.GetString("Paciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página de Inicio.
        /// </summary>
        internal static string PaginaInicio {
            get {
                return ResourceManager.GetString("PaginaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a la página anterior.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profesional.
        /// </summary>
        internal static string Profesional {
            get {
                return ResourceManager.GetString("Profesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recargar.
        /// </summary>
        internal static string Recargar {
            get {
                return ResourceManager.GetString("Recargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recargar.
        /// </summary>
        internal static string Refres {
            get {
                return ResourceManager.GetString("Refres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        internal static string Registrar {
            get {
                return ResourceManager.GetString("Registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regístrate.
        /// </summary>
        internal static string Registrate {
            get {
                return ResourceManager.GetString("Registrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro Correcto.
        /// </summary>
        internal static string RegistroCorrecto {
            get {
                return ResourceManager.GetString("RegistroCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultado.
        /// </summary>
        internal static string Resultado {
            get {
                return ResourceManager.GetString("Resultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a +593 (02)222 2222.
        /// </summary>
        internal static string TelefonoEmpresa {
            get {
                return ResourceManager.GetString("TelefonoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejemplo 02 222 2222.
        /// </summary>
        internal static string ToolTipoTelefonoConvencional {
            get {
                return ResourceManager.GetString("ToolTipoTelefonoConvencional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejemplo: 0987654321.
        /// </summary>
        internal static string ToolTipTelefonoCelular {
            get {
                return ResourceManager.GetString("ToolTipTelefonoCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        internal static string Ver {
            get {
                return ResourceManager.GetString("Ver", resourceCulture);
            }
        }
    }
}
